name: 'ESP-IDF v4.x build'
description: 'GitHub Action to build your ESP32 code using the official Docker container from Espressif.'

branding:
  icon: check
  color: purple
inputs:
  idf-target:
    description: 'IDF_TARGET, one of esp32, esp32s3 etc'
    required: true
outputs:
  result:
    description: 'The result code'

runs:
  using: 'docker'
  image: 'Dockerfile'
